services:
  backend:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    ports:
      - 8080:8080
  frontend:
    depends_on:
      - backend
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
      network: host
    ports:
      - 3000:8081
